layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

bio: "I enjoy watching movies, playing sports, playing video games, and listening to Radiohead.
"

about: "I'm Arian, a forth year Ph.D. candidate at <a href=\"https://cs.umass.edu/\">the University of Massachusetts, Amherst</a>. As a member of <a href=\"https://calipr.cs.umass.edu\">Calipr</a> Lab, I'm working under the supervision of <a href=\"https://people.cs.umass.edu/~phillipa/index.php\">Dr. Phillipa Gill</a>. My research interest broadly lies in the areas of networking and Internet measurement."

email: arian@cs.umass.edu

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: arian.niak
  # hackerrank: your_username
  instagram: ariannnak
  # keybase: your_username
  scholar: eqb_BD8AAAAJ
  linkedin: arian-niaki-221166109
  github: negarq
  # mastodon: your_username
  # medium: noidsirius
  # stackoverflow: 2681272/noidsirius
  # telegram: your_username
  # twitter: negarq
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

work:
  - company: "University of Massachusetts, Amherst"
    company_url: "https://calipr.cs.umass.edu"
    role: "Graduate Research Assistant"
    start: "August 2017"
    end: "Present"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Conducting research in the areas of Internet Measurement, Privacy and Security. </li>
      <li> Developing and maintaining a global <a href=\"https://iclab.org\">Internet Measurement Platform</a>. </li>
      <li> Investigating DNS over HTTPS and DNS over TLS. </li>
    </ul>"
  - company: "Thousand Eyes (Cisco)"
    company_url: "https://www.thousandeyes.com"
    role: "Research Intern"
    start: "June 2020"
    end: "September 2020"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Worked on analyzing and comparing CDN performance globally</li>
      <li> Analyzed web performance data from PSQL databases</li>
    </ul>"
  - company: "International Computer Science Institute (ICSI)"
    company_url: "http://icsi.berkeley.edu/"
    role: "Research Intern"
    start: "May 2018"
    end: "August 2018"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Worked on a research project about DNS cache probing </li>
      <li> Performed DNS cache probing to estimate the population of IoT devices </li>
    </ul>"
  - company: "Institute for Studies in Theoretical Physics and Mathematics (IPM), Tehran, Iran"
    company_url: "http://www.ipm.ac.ir"
    role: "Research Assistant"
    start: "June 2015"
    end: "July 2016"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Worked on Performance Modeling and Evaluation of Web Services Using High Level Extensions of Petri Nets. </li>
      <li> Supervised by Dr. Reza Entezari Maleki and Prof. Ali Movaghar </li>
    </ul>"
  - company: "Pishtazan Andishe Pouya, Tehran, Iran"
    company_url: ""
    role: "Software Engineering Intern"
    start: "January 2016"
    end: "July 2016"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Produced, designed and analyzed models for software information systems and
      web applications.</li>
      <li> Designed a database for web applications. </li>
    </ul>"
  - company: "VADA Future Communications,Tehran, Iran"
    company_url: "https://vada.ir"
    role: "Software Developer"
    start: "January 2014"
    end: "December 2014"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Developed several Android mobile applications </li>
      <li> Designed, developed, and maintained Django/Semantic-UI web applications </li>
      <li> Designed, developed a web crawler with Scrapy Spider </li>
    </ul>"


publication:
  - name: "Cache me Outside: A New Look at DNS Cache Probing"
    authors: "Arian Akhavan Niaki, William Marczak, Sahand Farhoodi, Andrew McGregor, Phillipa Gill and Nicholas Weaver"
    conference: "In Proceedings of the 22nd Passive and Active Measurement Conference (PAM 2021)"
    pdf: "https://link.springer.com/content/pdf/10.1007%2F978-3-030-72582-2_25.pdf"
  - name: "Triplet Censors: Demystifying Great Firewalls DNS Censorship Behavior"
    authors: "Anonymous, Arian Akhavan Niaki, Nguyen Phong Hoang, Phillipa Gill and Amir Houmansadr"
    conference: "In Proceedings of the 10th USENIX Workshop on Free and Open Communications on the Internet. FOCI 20. USENIX 2020"
    pdf: "https://www.usenix.org/system/files/foci20-paper-anonymous_0.pdf"
    video: "https://www.youtube.com/watch?v=ssG-mj2o_8o"
    repo: "https://gfw.report/publications/foci20_dns/en/"
  - name: "Assessing the Privacy Benefits of Domain Name Encryption"
    authors: "Nguyen Phong Hoang, Arian Akhavan Niaki, Nikita Borisov, Phillipa Gill and Michalis Polychronakis"
    conference: "In Proceedings of ACM ASIACCS 2020"
    pdf: "https://dl.acm.org/doi/pdf/10.1145/3320269.3384728"
    video: "https://dl.acm.org/doi/10.1145/3320269.3384728"
  - name: "The web is still small after more than a decade"
    authors: "Nguyen Phong Hoang, Arian Akhavan Niaki, Michalis Polychronakis and Phillipa Gill"
    conference: "In ACM SIGCOMM Computer Communication Review 2020"
    pdf: "https://dl.acm.org/doi/pdf/10.1145/3402413.3402417"
  - name: "A Global, Longitudinal Internet Censorship Measurement Platform"
    authors: "Arian Akhavan Niaki, Shinyoung Cho, Zachary Weinberg, Nguyen Phong Hoang, Abbas Razaghpanah, Nicolas Christin, and Phillipa Gill"
    conference: "Proceedings of the 41st IEEE Symposium on Security and Privacy (Oakland). IEEE. 2020"
    pdf: "https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9152784"
    video: "https://www.youtube.com/watch?v=Co9qRWFlQfs"
    repo: "https://iclab.org/post/iclab_data/"
  - name: "A Large-Scale Analysis of Deployed Traffic Differentiation Practices"
    authors: "Fangfan Li, Arian Akhavan Niaki, David Choffnes, Phillipa Gill, and Alan Mislove"
    conference: "In Proceedings of ACM SIGCOMM 2019"
    pdf: "https://dl.acm.org/doi/pdf/10.1145/3341302.3342092"    
    video: "https://dl.acm.org/doi/10.1145/3341302.3342092"
    repo: "http://dd.meddle.mobi"
  - name: "Studying TLS Usage in Android Apps"
    authors: "Abbas Razaghpanah, Arian Akhavan Niaki, Narseo Vallina-Rodriguez, Srikanth Sundaresan, Johanna Amann, and Phillipa Gill"
    conference: "Conference on emerging Networking EXperiments and Technologies (CoNEXT)"
    pdf: "https://dl.acm.org/doi/pdf/10.1145/3143361.3143400"    
    repo: "https://haystack.mobi/datasets.html"
  - name: "liberate (n): A library for exposing (traffic-classification) rules and avoiding them efficiently"
    authors: "Fangfan Li, Abbas Razaghpanah, Arash Molavi Kakhki, Arian Akhavan Niaki, David Choffnes, Phillipa Gill, and Alan Mislove"
    conference: "Internet Measurement Conference (IMC). London, UK."
    pdf: "https://dl.acm.org/doi/pdf/10.1145/3131365.3131376"    
    repo: "https://dd.meddle.mobi/liberate.html"
  - name: "Modeling and Evaluation of Service Composition in Commercial Multi-Clouds using Timed Colored Petri Nets"
    authors: "Reza Entezari-Maleki, Sayed Ehsan Etesami, <u>Negar Ghorbani</u>, Arian Akhavan Niaki, Leonel Sousa, Ali Movaghar"
    conference: "IEEE Transactions on Systems, Man, and Cybernetics: Systems, 2017"
    pdf: "https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8116749"



projects:
  - name: ICLab
    description: A global Internet censorship measurement project. 
    html_url: https://github.com/arianniaki/centinel
    source: github

  

# topics:
#   - name: Java

#   - name: Program Analysis

#   - name: Software Analysis and Testing

#   - name: Machine Learning for Automated Software Engineering

  # - name: CSS
  #   web_url: https://github.com/topics/css
  #   image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
  #   description: I learned something I learned something I learned something I learned something

  # - name: Web design

  # - name: Sass
  #   web_url: https://github.com/topics/sass
  #   image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png